require('dotenv').config();
CONFIG = {};
CONFIG.environment = process.env.APP;
CONFIG.db_host = process.env.DB_HOST;
CONFIG.db_port = process.env.DB_PORT || 8000;
CONFIG.db_name = process.env.DB_NAME;
CONFIG.db_user = process.env.DB_USER;
CONFIG.db_password = process.env.DB_PASSWORD;
CONFIG.db_dialect = process.env.DB_DIALECT;
CONFIG.secret_key = process.env.SECRET_KEY;
CONFIG.jwt_expiration = process.env.JWT_EXPIRATION;
CONFIG.mongo_db_name = process.env.MONGO_DB_NAME;
CONFIG.mongo_db_host = process.env.MONGO_DB_HOST;
CONFIG.mongo_db_port = process.env.MONGO_DB_PORT;
CONFIG.jwt_encryption = process.env.JWT_ENCRYPTION;